export const COMMUNES_40 = [
  "Longwy",
  "Longlaville",
  "Mont-Saint-Martin",
  "Herserange",
  "Réhon",
  "Lexy",
  "Mexy",
  "Cosnes-et-Romain",
  "Saulnes",
  "Haucourt-Moulaine",
  "Hussigny-Godbrange",
  "Gorcy",
  "Villerupt",
  "Audun-le-Tiche",
  "Morfontaine",
  "Fillières",
  "Tiercelet",
  "Villers-la-Montagne",
  "Ville-Houdlémont",
  "Cutry",
  "Chenières",
  "Laix",
  "Montigny-sur-Chiers",
  "Ugny",
  "Bréhain-la-Ville",
  "Thil",
  "Boismont",
  "Rédange",
  "Tellancourt",
  "Viviers-sur-Chiers",
  "Fresnois-la-Montagne",
  "Cons-la-Grandville",
  "Doncourt-lès-Longuyon",
  "Baslieux",
  "Ville-au-Montois",
  "Bazailles",
  "Joppécourt",
  "Mercy-le-Bas",
  "Mercy-le-Haut",
  "Xivry-Circourt"
].sort();

export const DATASETS = [
  { id: "dpe03existant", name: "DPE Logements Existants (V3 - Depuis 07/2021)" },
  { id: "dpe-v2-logements-neufs", name: "DPE Logements Neufs (V3 - Depuis 07/2021)" },
  { id: "dpe-france", name: "Ancien DPE (V1/V2 - 2013-2021)" }
];
