
export const COMMUNES_40 = [
  "Longwy",
  "Cosnes-et-Romain",
  "Lexy",
  "Villers-la-Montagne",
  "Mont-Saint-Martin",
  "Gorcy",
  "Herserange",
  "Réhon",
  "Mexy",
  "Haucourt-Moulaine",
  "Villers-la-Chèvre",
  "Longlaville",
  "Saulnes",
  "Hussigny-Godbrange",
  "Tiercelet",
  "Thil",
  "Villerupt",
  "Cutry",
  "Chenières",
  "Cons-la-Grandville",
  "Ugny",
  "Laix",
  "Baslieux",
  "Morfontaine",
  "Tellancourt",
  "Saint-Pancré",
  "Ville-Houdlémont",
  "Fresnois-la-Montagne",
  "Viviers-sur-Chiers",
  "Mont-Bonvillers",
  "Boismont",
  "Bazailles",
  "Pierrepont",
  "Beuveille",
  "Doncourt-lès-Longuyon",
  "Allondrelle-la-Malmaison",
  "Charency-Vezin",
  "Colmey",
  "Grand-Failly",
  "Petit-Failly",
  "Russange",
  "Rédange",
  "Audun-le-Tiche",
  "Ottange",
  "Aumetz"
].sort();

export const DATASETS = [
  { id: "dpe03existant", name: "DPE Logements Existants (V3 - Depuis 07/2021)" }
];
